### ISSUE TITLE
Wasn't sure how to let you know but I found two channels to add to your list

### ISSUE THREAD

**Issue by mystex** [blog-razrabotchika/homebridge-samsung-tizen-applications#1]
I found your list invaluable but it didn't have these two that I found.

"Amazon Music": "3201710014874"
"WeatherNation": "111399000085"

**Comment by Blackskydk** [comment]
"name": "Canal Digital",
"value": "3201605009379"

"name": "DRTV",
"value": "3201901017732"

"name": "Viaplay",
"value": "11111300404"

"name": "HBO Nordic",
"value": "111299002125"

 "name": "Steam Link",
 "value": "3201702011851"

**Comment by blog-razrabotchika** [comment]
> I found your list invaluable but it didn't have these two that I found.
> 
> "Amazon Music": "3201710014874"
> "WeatherNation": "111399000085"

thx

**Comment by blog-razrabotchika** [comment]
> "name": "Canal Digital",
> "value": "3201605009379"
> 
> "name": "DRTV",
> "value": "3201901017732"
> 
> "name": "Viaplay",
> "value": "11111300404"
> 
> "name": "HBO Nordic",
> "value": "111299002125"
> 
> "name": "Steam Link",
> "value": "3201702011851"

thx
